import React, { useState } from 'react';
import ReactMarkdown from 'react-markdown';
import { generateStudySchedule, isAiConfigured, checkAiServer } from '../services/geminiService';
import { StudyScheduleParams } from '../types';
import { useEffect, useState } from 'react';

export const StudyScheduler: React.FC = () => {
  const [status, setStatus] = useState<StudyScheduleParams['collegeStatus']>('attending');
  const [proff, setProff] = useState<StudyScheduleParams['proff']>('First');
  const [sleepTime, setSleepTime] = useState('23:00');
  const [wakeTime, setWakeTime] = useState('06:00');
  const [schedule, setSchedule] = useState('');
  const [loading, setLoading] = useState(false);
  const [aiAvailable, setAiAvailable] = useState<boolean | null>(null);

  useEffect(() => {
    let mounted = true;
    checkAiServer().then(ok => { if (mounted) setAiAvailable(ok); });
    return () => { mounted = false; };
  }, []);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    setLoading(true);
    setSchedule('');
    try {
      const result = await generateStudySchedule({ collegeStatus: status, proff, sleepTime, wakeTime });
      setSchedule(result);
    } catch (err) {
      setSchedule('Failed to generate schedule. Please try again.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <div className="max-w-4xl mx-auto py-12 px-4">
      <div className="text-center mb-10">
        <h2 className="text-3xl font-bold text-ayur-brown mb-2">Smart Study Scheduler</h2>
        <p className="text-gray-600">Get a practical, Ayurvedic-aligned study routine generated by AI based on your year and lifestyle.</p>
        {aiAvailable === false && (
          <div className="mt-3 text-sm text-yellow-700 bg-yellow-50 border border-yellow-200 px-3 py-2 rounded">
            AI is not available on the server. Set `GEMINI_API_KEY` in Vercel project settings.
          </div>
        )}
      </div>

      <div className="grid md:grid-cols-2 gap-8">
        {/* Form */}
        <div className="bg-white p-6 rounded-xl shadow-lg border-t-4 border-ayur-saffron h-fit">
          <form onSubmit={handleSubmit} className="space-y-6">
            
            {/* Proff Selection */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">Professional Year (18 Months)</label>
              <div className="grid grid-cols-3 gap-2">
                {['First', 'Second', 'Third'].map((p) => (
                  <button
                    key={p}
                    type="button"
                    onClick={() => setProff(p as any)}
                    className={`py-2 px-1 text-sm rounded border transition-all font-medium ${
                      proff === p
                        ? 'bg-ayur-green text-white border-ayur-green' 
                        : 'bg-gray-50 text-gray-600 border-gray-200 hover:border-ayur-green'
                    }`}
                  >
                    {p} Proff
                  </button>
                ))}
              </div>
            </div>

            {/* Status Selection */}
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-2">College Status</label>
              <div className="grid grid-cols-3 gap-2">
                {[
                  { id: 'attending', label: 'Attending' },
                  { id: 'non-attending', label: 'Non-Attending' },
                  { id: 'weekend', label: 'Weekend Batch' }
                ].map((type) => (
                  <button
                    key={type.id}
                    type="button"
                    onClick={() => setStatus(type.id as any)}
                    className={`py-2 px-1 text-sm rounded border transition-all font-medium ${
                      status === type.id 
                        ? 'bg-ayur-saffron text-white border-ayur-saffron' 
                        : 'bg-gray-50 text-gray-600 border-gray-200 hover:border-ayur-saffron'
                    }`}
                  >
                    {type.label}
                  </button>
                ))}
              </div>
            </div>

            {/* Time Selection */}
            <div className="grid grid-cols-2 gap-4">
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Sleep Time</label>
                <input 
                  type="time" 
                  value={sleepTime}
                  onChange={(e) => setSleepTime(e.target.value)}
                  className="w-full p-2 border border-gray-300 rounded focus:border-ayur-green outline-none"
                />
              </div>
              <div>
                <label className="block text-sm font-semibold text-gray-700 mb-2">Wake Time</label>
                <input 
                  type="time" 
                  value={wakeTime}
                  onChange={(e) => setWakeTime(e.target.value)}
                  className="w-full p-2 border border-gray-300 rounded focus:border-ayur-green outline-none"
                />
              </div>
            </div>

            <button
              type="submit"
              disabled={loading || aiAvailable === false}
              className="w-full bg-gradient-to-r from-ayur-green to-green-700 text-white py-3 rounded-lg font-bold shadow-md hover:shadow-lg transition-all flex justify-center items-center gap-2"
            >
              {loading ? (
                <>
                  <i className="fas fa-spinner fa-spin"></i> Generating...
                </>
              ) : (
                <>
                  <i className="fas fa-magic"></i> Generate Plan
                </>
              )}
            </button>
          </form>
        </div>

        {/* Result */}
        <div className="bg-white p-6 rounded-xl shadow-lg min-h-[400px] border-t-4 border-ayur-green relative flex flex-col">
           {!schedule && !loading && (
             <div className="absolute inset-0 flex flex-col items-center justify-center text-gray-400 p-6 text-center">
               <i className="fas fa-calendar-alt text-4xl mb-3"></i>
               <p>Your personalized schedule for the new BAMS curriculum will appear here.</p>
             </div>
           )}
           {loading && (
             <div className="absolute inset-0 flex flex-col items-center justify-center text-ayur-saffron p-6 text-center">
               <i className="fas fa-circle-notch fa-spin text-4xl mb-3"></i>
               <p>Consulting the new syllabus and calculating optimum study hours...</p>
             </div>
           )}
           {schedule && (
             <div className="prose prose-sm max-w-none text-gray-700 overflow-y-auto max-h-[500px] pr-2 flex-grow">
               <ReactMarkdown>{schedule}</ReactMarkdown>
             </div>
           )}
        </div>
      </div>
    </div>
  );
};
